# build a domain-server using vircadia-builder
FROM ubuntu:18.04 as domain-server-build

RUN echo UTC >/etc/timezone

# The tag to pull from the Project Athena source repository. (Note defn in next stage)
ARG REPO=https://github.com/vircadia/vircadia
ARG TAG=master

# Tell the libraries not to use the interactive dialogs
ARG DEBIAN_FRONTEND=noninteractive
ARG TERM=linux

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y git vim libfindbin-libs-perl sudo

RUN mkdir -p /var/lib/vircadia
RUN mkdir -p /opt/vircadia

#    && git clone --branch feature-optSkipSystemdRestart https://github.com/misterblue/vircadia-builder.git \
# Get the builder
RUN cd /opt/vircadia \
    && git clone https://github.com/daleglass/vircadia-builder.git \
    && cd vircadia-builder \
    && chmod +x vircadia-builder

# Load the required libraries (the first time just loads packages)
RUN cd /opt/vircadia/vircadia-builder \
    && ./vircadia-builder \
            --repo=$REPO \
            --tag=$TAG \
            --build=domain-server,assignment-client,ice-server \
            --destdir /opt/vircadia \
            --auto

# Create a list of all the source dependencies needed for later phase
RUN cd /opt/vircadia/vircadia-builder \
    && ./vircadia-builder \
            --repo=$REPO \
            --tag=$TAG \
            --destdir /opt/vircadia \
            --keep-source \
            --get-source-deps ubuntu-18.04 \
            --auto > /opt/vircadia/builder-deps.txt

# Build the server pieces
RUN cd /opt/vircadia/vircadia-builder \
    && ./vircadia-builder \
            --repo=$REPO \
            --tag=$TAG \
            --destdir /opt/vircadia \
            --keep-source \
            --build=domain-server,assignment-client,ice-server \
            --skip-systemd-restart \
            --auto

COPY files/buildVersion.sh /tmp
RUN mkdir -p /opt/vircadia/version \
    && /tmp/buildVersion.sh /opt/vircadia/source /opt/vircadia/version $TAG
